# basic vars to make the templates cleaner
network_os: "{{ rm['NETWORK_OS'] }}"
resource: "{{ rm['RESOURCE'] }}"

# set transport to network_cli unless overridden in cli
transport: network_cli

# set the directory for modules based on the structure
module_directories:
  role: library
  collection: modules

module_directory: "{{ module_directories[structure] }}"

# set the parent directory based on the structure
parent_directories:
  role: ''
  collection: /plugins

parent_directory: "{{ rm_dest }}{{ parent_directories[structure] }}"

# set the iport path based on the structure
import_paths:
  role: ansible.module_utils
  collection: "ansible_collections.{{ collection_org|default('') }}.{{ collection_name|default('') }}.plugins.module_utils"

import_path: "{{ import_paths[structure] }}.network"

# all the directories that need to be built
resource_module_directories:
- "{{ module_directory }}"
- module_utils
- module_utils/network
- module_utils/network/{{ network_os }}
- module_utils/network/{{ network_os }}/argspec
- module_utils/network/{{ network_os }}/argspec/facts
- module_utils/network/{{ network_os }}/argspec/{{ resource }}
- module_utils/network/{{ network_os }}/config
- module_utils/network/{{ network_os }}/config/{{ resource }}
- module_utils/network/{{ network_os }}/facts
- module_utils/network/{{ network_os }}/facts/{{ resource }}
- module_utils/network/{{ network_os }}/utils

# each of the files to be templated
resource_module_templates:
- source: README.md.j2
  destination: "{{ rm_dest }}/README.md"
  overwrite: False
- source: module_directory/network_os/network_os_resource.py.j2
  destination: "{{ parent_directory }}/{{ module_directory }}/{{ network_os }}_{{ resource }}.py"
  overwrite: True
- source: module_directory/network_os/network_os_facts.py.j2
  destination: "{{ parent_directory }}/{{ module_directory }}/{{ network_os }}_facts.py"
  overwrite: False
- source: module_utils/network_os/argspec/facts/facts.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/argspec/facts/facts.py"
  overwrite: False
- source: module_utils/network_os/argspec/resource/resource.py.j2
  destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/argspec/{{ resource }}/{{ resource }}.py"
  overwrite: True
- source: module_utils/network_os/config/resource/resource.py.j2
  destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/config/{{ resource }}/{{ resource }}.py"
  overwrite: False
- source: module_utils/network_os/facts/facts.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/facts/facts.py"
  overwrite: False
- source: module_utils/network_os/facts/resource/resource.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/facts/{{ resource }}/{{ resource }}.py"
  overwrite: False
- source: module_utils/network_os/utils/utils.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/utils/utils.py"
  overwrite: False
