# basic vars to make the templates cleaner
copyright: "Copyright {{ ansible_date_time.year }} Red Hat"
version_added: "1.0.0"
temp: "/tmp/{{ ansible_date_time.iso8601_basic|hash('md5') }}"

# set transport to network_cli unless overridden in cli
transport: network_cli

parent_directory: "{{ rm_dest }}/plugins"

import_path: "ansible_collections.{{ collection_org|default('') }}.{{ collection_name|default('') }}.plugins.module_utils.network"

# all the directories that need to be built
resource_module_directories:
- modules
- module_utils
- module_utils/network
- module_utils/network/{{ network_os }}
- module_utils/network/{{ network_os }}/argspec
- module_utils/network/{{ network_os }}/argspec/facts
- module_utils/network/{{ network_os }}/argspec/{{ resource }}
- module_utils/network/{{ network_os }}/config
- module_utils/network/{{ network_os }}/config/{{ resource }}
- module_utils/network/{{ network_os }}/facts
- module_utils/network/{{ network_os }}/facts/{{ resource }}
- module_utils/network/{{ network_os }}/rm_templates
- module_utils/network/{{ network_os }}/utils
- action
- filter
- inventory

# each of the files to be templated
resource_module_templates:
- source: README.md.j2
  destination: "{{ rm_dest }}/README.md"
  overwrite: False
- source: module_directory/network_os/network_os_resource.py.j2
  destination: "{{ parent_directory }}/modules/{{ network_os }}_{{ resource }}.py"
  overwrite: True
- source: module_directory/network_os/network_os_facts.py.j2
  destination: "{{ parent_directory }}/modules/{{ network_os }}_facts.py"
  overwrite: False
- source: module_utils/network_os/argspec/facts/facts.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/argspec/facts/facts.py"
  overwrite: False
- source: module_utils/network_os/argspec/resource/resource.py.j2
  destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/argspec/{{ resource }}/{{ resource }}.py"
  overwrite: True
- source: module_utils/network_os/config/resource/resource.py.j2
  destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/config/{{ resource }}/{{ resource }}.py"
  overwrite: False
- source: module_utils/network_os/facts/facts.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/facts/facts.py"
  overwrite: False
- source: module_utils/network_os/facts/resource/resource.py.j2
  destination: "{{ parent_directory}}/module_utils/network/{{ network_os }}/facts/{{ resource }}/{{ resource }}.py"
  overwrite: False
- source: module_utils/network_os/rm_templates/resource.py.j2
  destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/rm_templates/{{ resource }}.py"
  overwrite: False
- source: module_utils/network_os/utils/utils.py.j2
  destination: "{{ parent_directory }}/module_utils/network/{{ network_os }}/utils/utils.py"
  overwrite: False
