directories:
  collection:
  - plugins/modules
  - plugins/module_utils
  - plugins/filter
  - plugins/action
  - plugins/inventory
  - playbooks
  - docs
  - roles
  role:
  - library
  - module_utils
